# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-27 18:38
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0005_auto_20151026_1600'),
        ('shop', '0008_auto_20170426_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.IntegerField(default=0, editable=False, verbose_name='Download Count')),
                ('download_limit', models.IntegerField(default=100, verbose_name='Download Limit')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/home/skru/Projects/ipra/project/my_cms/private_downloads/', location='/home/skru/Projects/ipra/project/my_cms/private_downloads/'), upload_to='')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('forms', models.ManyToManyField(related_name='downloads', to='forms.Form')),
                ('products', models.ManyToManyField(related_name='downloads', to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('acquisition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cartridge_downloads.Acquisition')),
                ('formentry', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='forms.FormEntry')),
            ],
            bases=('cartridge_downloads.acquisition',),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('acquisition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cartridge_downloads.Acquisition')),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='shop.Order')),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='shop.Product')),
            ],
            bases=('cartridge_downloads.acquisition',),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='download',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cartridge_downloads.Download'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cartridge_downloads.Transaction'),
        ),
    ]
